steps:
- name: 'gcr.io/$PROJECT_ID/yarn-builder'
  entrypoint: 'yarn'
  args: ['install', '--frozen-lockfile', '--non-interactive', '--no-progress']
- name: 'gcr.io/$PROJECT_ID/yarn-builder'
  entrypoint: 'yarn'
  args: ['release', '$PROJECT_ID']
- name: gcr.io/clingen-stage/firebase
  args: ['deploy', '--project=$PROJECT_ID', '--only=hosting']
